// Generated by ReScript, PLEASE EDIT WITH CARE


var Link = {};

var $$History = {};

var BrowserRouter = {};

var Switch = {};

var Route = {};

export {
  Link ,
  $$History ,
  BrowserRouter ,
  Switch ,
  Route ,
  
}
/* No side effect */
